server:
  port: 10000

#Eureka配置
eureka:
  client:
    register-with-eureka: false #不向Eureka注册自己
    service-url:
      defaultZone: http://localhost:7001/eureka/

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB


